# Generated by Django 3.1.4 on 2021-04-08 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('color', models.CharField(choices=[('赤', 'Red'), ('青', 'Bleu'), ('白', 'White'), ('黒', 'Black'), ('黄', 'Yellow'), ('緑', 'Green')], max_length=1, verbose_name='カラー')),
                ('shop1', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=60, verbose_name='車名')),
                ('car_menu', models.CharField(choices=[('SP', 'Sports'), ('SUV', 'SUV'), ('SD', 'Sedan'), ('TR', 'Trucks'), ('SW', 'StationWagon')], max_length=3, verbose_name='タイプ')),
                ('car_drive', models.CharField(choices=[('前輪駆動', 'FF'), ('後輪駆動', 'FR'), ('4輪駆動', '4WD'), ('ミッドシップ', 'MR')], max_length=6, verbose_name='駆動方式')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer')),
            ],
        ),
    ]
