# Generated by Django 3.1.4 on 2021-04-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_name', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='車名')),
                ('car_menu', models.CharField(choices=[('SP', 'Sports'), ('SUV', 'SUV'), ('SD', 'Sedan'), ('TR', 'Trucks'), ('SW', 'StationWagon')], max_length=3, verbose_name='タイプ')),
                ('car_drive', models.CharField(choices=[('前輪駆動', 'FF'), ('後輪駆動', 'FR'), ('4輪駆動', '4WD'), ('ミッドシップ', 'MR')], max_length=6, verbose_name='駆動方式')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
