# Generated by Django 3.1.4 on 2021-04-12 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('shop1', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('named_picture', models.CharField(max_length=200)),
                ('car_name', models.CharField(max_length=60, verbose_name='車名')),
                ('car_menu', models.CharField(choices=[('SP', 'Sports'), ('SUV', 'SUV'), ('SD', 'Sedan'), ('TR', 'Trucks'), ('SW', 'StationWagon')], max_length=3, verbose_name='タイプ')),
                ('drive_system', models.CharField(choices=[('オートマ', 'AT・CVT'), ('マニュアル', 'MT')], max_length=6, verbose_name='タイプ')),
                ('car_drive', models.CharField(choices=[('前輪駆動', 'FF'), ('後輪駆動', 'FR'), ('4輪駆動', '4WD'), ('ミッドシップ', 'MR')], max_length=6, verbose_name='駆動方式')),
                ('odometer1', models.CharField(max_length=6, verbose_name='走行距離')),
                ('odometer2', models.CharField(choices=[('50,000_or_less', '5万キロ未満'), ('over_50,000', '5万キロ以上'), ('over_100,000', '10万キロ以上')], max_length=14, verbose_name='走行距離')),
                ('car_repaired', models.CharField(choices=[('yes', '修復歴有り'), ('no', '修復歴無し')], max_length=5, verbose_name='修復歴')),
                ('color', models.CharField(choices=[('Red', 'レッド'), ('Bleu', 'ブルー'), ('White', 'ホワイト'), ('Black', 'ブラック'), ('Yellow', 'イエロー'), ('Green', 'グリーン'), ('Decorated car', '痛車')], max_length=15, verbose_name='車の色')),
                ('kanto', models.CharField(choices=[('Kanagawa', '神奈川県'), ('Tokyo', '東京都'), ('Saitama', '埼玉県'), ('Chiba', '千葉県'), ('Gunma', '群馬県'), ('Ibaraki', '茨城県')], max_length=10, verbose_name='関東地方')),
                ('city', models.CharField(max_length=60, verbose_name='市')),
                ('area', models.CharField(max_length=60, verbose_name='区・町・村')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer')),
            ],
        ),
    ]
