# Generated by Django 3.1.4 on 2021-04-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(default=1234, upload_to=''),
            preserve_default=False,
        ),
    ]
