# Generated by Django 3.1.4 on 2021-04-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='odometer1',
            field=models.CharField(max_length=7, verbose_name='走行距離'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(choices=[('トヨタ', 'TOYOTA'), ('レクサス', 'LEXUS'), ('日産', 'NISSAN'), ('ホンダ', 'HONDA'), ('スバル', 'SUBARU'), ('三菱', 'MITSUBISHI'), ('マツダ', 'MAZDA'), ('スズキ', 'SUZUKI'), ('ダイハツ', 'DAIHATSU'), ('光岡', 'MITSUOKA'), ('いすゞ', 'ISUZU')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
