# Generated by Django 3.1.4 on 2021-04-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210413_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='named_picture',
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_model',
            field=models.CharField(default=1234, max_length=200, verbose_name='車両型式'),
            preserve_default=False,
        ),
    ]
