# Generated by Django 3.1.4 on 2021-04-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer'),
            preserve_default=False,
        ),
    ]
