# Generated by Django 3.1.4 on 2021-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
        migrations.AddField(
            model_name='car',
            name='named_picture',
            field=models.CharField(default=4567, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(default=4567, upload_to='images/'),
            preserve_default=False,
        ),
    ]
