# Generated by Django 3.1.4 on 2021-04-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210408_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('赤', 'Red'), ('青', 'Bleu'), ('白', 'White'), ('黒', 'Black'), ('黄', 'Yellow'), ('緑', 'Green'), ('痛車', 'Decorated car')], default=6789, max_length=2, verbose_name='カラー'),
            preserve_default=False,
        ),
    ]
