# Generated by Django 3.1.4 on 2021-04-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='id',
            field=models.AutoField(auto_created=True, default=1234, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturer',
        ),
    ]
