# Generated by Django 3.1.4 on 2021-04-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210407_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.AutoField(auto_created=True, default=4567, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=60, verbose_name='車名'),
        ),
    ]
