# Generated by Django 3.1.4 on 2021-04-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210411_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', '赤'), ('Bleu', '青'), ('White', '白'), ('Black', '黒'), ('Yellow', '黄'), ('Green', '緑'), ('Decorated car', '痛車')], max_length=15, verbose_name='カラー'),
        ),
    ]
