# Generated by Django 3.1.4 on 2021-04-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210407_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='id',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
