# Generated by Django 3.1.4 on 2021-04-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_kanto_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kanto_area',
            field=models.CharField(choices=[('神奈川県', 'Kanagawa'), ('東京都', 'Tokyo'), ('埼玉県', 'Saitama'), ('千葉県', 'Chiba'), ('群馬県', 'Gunma'), ('茨城県', 'Ibaraki')], max_length=10, verbose_name='関東地方'),
        ),
    ]
