# Generated by Django 3.1.4 on 2021-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210411_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='kanto_area',
        ),
        migrations.AddField(
            model_name='car',
            name='area',
            field=models.CharField(default=4560, max_length=60, verbose_name='区・町・村'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='car_repaired',
            field=models.CharField(choices=[('yes', '修復歴有り'), ('no', '修復歴無し')], default=7890, max_length=5, verbose_name='修復歴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default=1230, max_length=60, verbose_name='市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='drive_system',
            field=models.CharField(choices=[('オートマ', 'AT・CVT'), ('マニュアル', 'MT')], default=1123, max_length=6, verbose_name='タイプ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='kanto',
            field=models.CharField(choices=[('Kanagawa', '神奈川県'), ('Tokyo', '東京都'), ('Saitama', '埼玉県'), ('Chiba', '千葉県'), ('Gunma', '群馬県'), ('Ibaraki', '茨城県')], default=1041, max_length=10, verbose_name='関東地方'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='odometer1',
            field=models.CharField(default=1054, max_length=6, verbose_name='走行距離'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='odometer2',
            field=models.CharField(choices=[('50,000_or_less', '5万キロ未満'), ('over_50,000', '5万キロ以上'), ('over_100,000', '10万キロ以上')], default=2127, max_length=14, verbose_name='走行距離'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', 'レッド'), ('Bleu', 'ブルー'), ('White', 'ホワイト'), ('Black', 'ブラック'), ('Yellow', 'イエロー'), ('Green', 'グリーン'), ('Decorated car', '痛車')], max_length=15, verbose_name='車の色'),
        ),
    ]
